version: 2
jobs:
  build:
    working_directory: ~/HelloWorld
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run: mvn package
